name: ✨ Feature Request
description: Suggest a new feature or enhancement for Insiab SPM/PPM Platform
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below to help us understand your request.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief summary of the feature you'd like to see.
      placeholder: What feature would you like to add?
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What user need does it address?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Describe how users would interact with this feature.
      placeholder: |
        As a [type of user], I want [goal] so that [benefit].
        
        Example:
        - As a project manager, I want to bulk assign tasks so that I can efficiently distribute work to my team.
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: Primary User Type
      description: Who would primarily benefit from this feature?
      options:
        - Project Manager
        - Portfolio Manager
        - Team Member
        - Executive/Stakeholder
        - System Administrator
        - All Users
    validations:
      required: true

  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which area of the application would this feature belong to?
      options:
        - Projects
        - Portfolios
        - Programs
        - Tasks
        - Kanban Boards
        - Analytics & Reporting
        - Collaboration
        - Mobile
        - Integrations
        - AI & Automation
        - User Management
        - Settings
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking my work)
        - High (would significantly improve my workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or features?
      placeholder: Describe any alternative approaches you've considered...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If you have any mockups, wireframes, or examples from other tools, please share them.
      placeholder: Drag and drop images here or describe the UI/UX you envision...

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small UI change, no new data models)
        - Medium (new components, some backend changes)
        - Complex (new data models, significant backend work)
        - Very Complex (major architectural changes)
        - Not sure

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, links, or information about the feature request.
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: terms
    attributes:
      label: Verification
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests before creating this one
          required: true
        - label: This feature aligns with the project's goals and roadmap
          required: true